CREATE TABLE IF NOT EXISTS agent_reviews (
  review_id VARCHAR(50) PRIMARY KEY,
  commit_hash VARCHAR(64),
  model VARCHAR(100) NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE,
  service VARCHAR(100),
  flow_status VARCHAR(40) NOT NULL,
  decision VARCHAR(30),
  risk_level VARCHAR(30),
  build_status VARCHAR(30),
  tests_status VARCHAR(30),
  skipped_tests INTEGER NOT NULL DEFAULT 0,
  security_status VARCHAR(30),
  security_matches INTEGER NOT NULL DEFAULT 0,
  approval_status VARCHAR(40),
  recommended_action VARCHAR(40),
  action_token_hash BINARY(32),
  action VARCHAR(40),
  reason VARCHAR(500),
  decided_at TIMESTAMP WITH TIME ZONE,
  reviewer_identity_status VARCHAR(40) NOT NULL DEFAULT 'NOT_AUTHENTICATED'
);

CREATE TABLE IF NOT EXISTS agent_tool_executions (
  execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id VARCHAR(50) NOT NULL REFERENCES agent_reviews(review_id),
  tool VARCHAR(40) NOT NULL,
  input VARCHAR(240) NOT NULL,
  status VARCHAR(40) NOT NULL,
  duration_ms BIGINT NOT NULL,
  executed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_tool_executions_review
  ON agent_tool_executions(review_id, execution_id);

CREATE TABLE IF NOT EXISTS agent_review_actions (
  action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id VARCHAR(50) NOT NULL REFERENCES agent_reviews(review_id),
  action VARCHAR(40) NOT NULL,
  decided_at TIMESTAMP WITH TIME ZONE NOT NULL,
  reviewer_identity_status VARCHAR(40) NOT NULL
);
