package com.example.platform.gateway.error;

import java.time.Instant;

/** Stable public error contract for failures generated by the gateway. */
public record GatewayErrorResponse(
        Instant timestamp,
        int status,
        String code,
        String message,
        String path,
        String correlationId) {
}
